Moved CSS to one file
Blackcipher101/CamScanner_webapp pull request #3
Opened 2020-09-03 16:10 UTC by tanvee09

2020-09-08 09:08 UTC, Blackcipher101 requested changes
Could you attach the screen shot 
And a small tip add which issue you would this pull request would solve :smile:

2020-09-09 05:11 UTC, tanvee09 commented
![Screenshot from 2020-09-09 10-36-13](https://user-images.githubusercontent.com/65037396/92556874-9e16f480-f288-11ea-8b28-06e01dd9ad9b.png)
![Screenshot from 2020-09-09 10-36-17](https://user-images.githubusercontent.com/65037396/92556881-9fe0b800-f288-11ea-8a05-2badb9c4e40d.png)
![Screenshot from 2020-09-09 10-36-20](https://user-images.githubusercontent.com/65037396/92556885-a2dba880-f288-11ea-8e79-f6f84d1dd735.png)
![Screenshot from 2020-09-09 10-36-23](https://user-images.githubusercontent.com/65037396/92556891-a707c600-f288-11ea-8a7f-154bdaed5c6e.png)
![Screenshot from 2020-09-09 10-36-27](https://user-images.githubusercontent.com/65037396/92556896-aa02b680-f288-11ea-8775-343e2164d207.png)
![Screenshot from 2020-09-09 10-36-31](https://user-images.githubusercontent.com/65037396/92556904-ae2ed400-f288-11ea-9ce7-4b7581fdf62f.png)
![Screenshot from 2020-09-09 10-36-38](https://user-images.githubusercontent.com/65037396/92556914-b25af180-f288-11ea-9a43-3ce2bdd8ec1b.png)
![Screenshot from 2020-09-09 10-36-42](https://user-images.githubusercontent.com/65037396/92556922-b4bd4b80-f288-11ea-9ee7-1a3a8c233960.png)
![Screenshot from 2020-09-09 10-36-47](https://user-images.githubusercontent.com/65037396/92556929-b850d280-f288-11ea-8315-33bce310be67.png)
![Screenshot from 2020-09-09 10-37-07](https://user-images.githubusercontent.com/65037396/92556934-bbe45980-f288-11ea-81ee-793ee0204a90.png)
  
Thank you for the feedback and tip!

2020-09-09 05:17 UTC, Blackcipher101 approved these changes

2020-09-09 05:19 UTC, Blackcipher101 commented
Thanks I just wanted the screenshot of website.... Not all the changes :P

2020-09-09 05:19 UTC, merged